name = "Demo"
uuid = "7ad3dd93-4604-4db8-99e2-96696e97842a"
authors = ["Ulrich Aïvodji"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
